dist: trusty
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi doxygen graphviz
install:
  - cd docs && virtualenv _venv && source _venv/bin/activate && pip install -r requirements.txt && cd ..
script:
  - for i in src/flavours/*; do FLAVOUR=${i#src/flavours/} make clean && FLAVOUR=${i#src/flavours/} make && FLAVOUR=${i#src/flavours/} make clean; done
  - cd docs && make html && cd ..
  - make test
  - for i in src/flavours/*; do FLAVOUR=${i#src/flavours/} make clean && FLAVOUR=${i#src/flavours/} DEBUG_BUILD=no make && FLAVOUR=${i#src/flavours/} make clean; done
